apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: namespace-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        ports:
        - containerPort: 80

--------------------------------

apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: namespace-1
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

--------------------------------

kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: httpd-proxy
  namespace: namespace-1
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: httpd-service
          port: 80
      loadBalancerPolicy:
        strategy: WeightedLeastRequest
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: httpd-contour.abc.com
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
      allowHeaders:
        - "*" # allows any origin
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
    tls:
      secretName: httpd-proxy

--------------------------------



apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: admin@abc.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour

--------------------------------

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpd-proxy
spec:
  commonName: httpd-contour.abc.com
  dnsNames:
    -  httpd-contour.abc.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: httpd-proxy
